name: nufa-test-task
channels:
  - defaults
dependencies:
  - pip:
      - git+https://github.com/huggingface/diffusers
      - accelerate==0.18.0
      - click==8.1.3
      - pillow==9.5.0
      - scipy==1.10.1
      - tokenizers==0.13.3
      - torch==2.0.1
      - torch-fidelity==0.3.0
      - torchmetrics==0.11.4
      - torchvision==0.15.2
      - tqdm==4.65.0
      - transformers==4.27.3
      - xformers==0.0.20
